### ISSUE TITLE
How can I extend this code for data with arbitrary channel？

### ISSUE THREAD

**Issue by sdujump** [gfacciol/pypatchmatch#1]

**Comment by gfacciol** [comment]
The code already contemplates arbitrary number of channels.
Just try matching these 4-channel pngs. They are black in the first 3 channels, the image is in the 4th channel (alpha).

![f](https://cloud.githubusercontent.com/assets/5002346/26819274/74b0f57c-4a9e-11e7-98a4-d47f888a7de0.png)
![g](https://cloud.githubusercontent.com/assets/5002346/26819275/74c26726-4a9e-11e7-8a6a-809c7f6f3dff.png)

**Comment by sdujump** [comment]
Thanks. It works well.
But I found the runing time is increasing lineally as the channels of data increased. Why the number of channels could effect running time so much?

**Comment by gfacciol** [comment]
Well, that's because the patch comparison operation must look at all the channels, right?
If you have many many channels, chances are that they'll be redundant. In that case to speed-up matching you can reduce the dimensionality of your data across the channels with PCA or something.
